socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & 
docker run -e DISPLAY=docker.for.mac.host.internal:0 jess/tor-browser
docker run -e DISPLAY=docker.for.mac.host.internal:0 fbfa439e3b79
